### ISSUE TITLE
Checking foreign neighbors

### ISSUE THREAD

**Issue by OleksandrKvitka** [akorunska/euro-diffusion#3]
https://github.com/akorunska/euro-diffusion/blob/8ed415057c9da83bac766db8b6b4811d96c9d81f/src/country.py#L30-L36

It makes sence to check only borderline cities in country, internal cities definitely won't have foreign neighbors.
Also, keeping boolean variable is not necessary, as well as continue the loop if conditional is already true.

**Comment by akorunska** [comment]
Unnecessary variable was removed in https://github.com/akorunska/euro-diffusion/commit/fad35ce0e92f02bb811cd2ede7cd08b7547a3e5e 

Search in the cities, however, can hardly be refactored in the following implementation. Since cities of each country are stored in a list and it's one dimensional, all cities have to be traversed in order to find 'border' ones. Adding additional check for lying on border will not help in optimizing execution. 
I suggest it to be left it as it is.

**Comment by OleksandrKvitka** [comment]
Ok, I'm agree.
