### ISSUE TITLE
More descriptive names

### ISSUE THREAD

**Issue by IanaKhitsko** [akorunska/euro-diffusion#7]
https://github.com/akorunska/euro-diffusion/blob/0988f5fe91d81d85725e8687c12c01fe7cf9b552/src/country.py#L31-L32

please give more descriptive names for c,n

**Comment by akorunska** [comment]
https://github.com/akorunska/euro-diffusion/blob/e789a8e90bb7d5bd2c4e8222aaef969e261fb5f8/src/country.py#L31-L32
https://github.com/akorunska/euro-diffusion/blob/e789a8e90bb7d5bd2c4e8222aaef969e261fb5f8/src/city.py#L24-L26

Fixed in https://github.com/akorunska/euro-diffusion/commit/e789a8e90bb7d5bd2c4e8222aaef969e261fb5f8 
I suggest we close this issue.
