### ISSUE TITLE
Get rid of acronyms

### ISSUE THREAD

**Issue by IanaKhitsko** [akorunska/euro-diffusion#8]
https://github.com/akorunska/euro-diffusion/blob/0988f5fe91d81d85725e8687c12c01fe7cf9b552/src/map.py#L26

Please get rid of these acronyms , give more descriptive names to the variables

**Comment by akorunska** [comment]
https://github.com/akorunska/euro-diffusion/blob/356866a436056aa71ec4a5d422754253bb3a502a/src/map.py#L26-L27
https://github.com/akorunska/euro-diffusion/blob/356866a436056aa71ec4a5d422754253bb3a502a/src/map.py#L62-L66

Fixed in https://github.com/akorunska/euro-diffusion/commit/147e1efe137612a9284182ce10b25c1796a006ee
I suggest we close this issue.
