### ISSUE TITLE
Break here?

### ISSUE THREAD

**Issue by IanaKhitsko** [akorunska/euro-diffusion#9]
https://github.com/akorunska/euro-diffusion/blob/0988f5fe91d81d85725e8687c12c01fe7cf9b552/src/map.py#L41

Do we need to break the cycle?

**Comment by akorunska** [comment]
Yes, it would have been a little bit more efficient in the old implementation, but new one suggests that this loop also runs check_fullness on each country in it, so breaking loop would lead to incorrect behavior:
https://github.com/akorunska/euro-diffusion/blob/356866a436056aa71ec4a5d422754253bb3a502a/src/map.py#L36-L39 

But if you mean breaking outer loop, then on the contrary, by setting full to false we ensure that next cycle of while loop is run and next day is simulated. Breaking instead of assigning full to False would cause infinite loop, since day would not be incremented.

Anyway I suggest to close this issue.
